<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Server\Yashdeep.Server.Api\Yashdeep.Server.Api.csproj" />
    <ProjectReference Include="..\..\src\Application\Yashdeep.Application\Yashdeep.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\Yashdeep.Domain\Yashdeep.Domain.csproj" />
    <ProjectReference Include="..\..\src\Shared\Yashdeep.Shared\Yashdeep.Shared.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Yashdeep.Infrastructure\Yashdeep.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Yashdeep.Persistence.Cloud\Yashdeep.Persistence.Cloud.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Yashdeep.Persistence.Local\Yashdeep.Persistence.Local.csproj" />
    <ProjectReference Include="..\..\src\SyncEngine\Yashdeep.SyncEngine\Yashdeep.SyncEngine.csproj" />
    <ProjectReference Include="..\..\src\Client\Yashdeep.Client.Blazor\Yashdeep.Client.Blazor.csproj" />
    <ProjectReference Include="..\..\src\Client\Yashdeep.Client.Maui\Yashdeep.Client.Maui.csproj" />
  </ItemGroup>

</Project>