-- Schema extracted from YashdeepHotelMS dinurss.mdb
-- Password: <PRODUCTION_MDB_PASSWORD>
-- Date: 2026-09-13 18:02:21

CREATE TABLE [AccountHead] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [mobile] TEXT NOT NULL,
    [credit] DOUBLE PRECISION NOT NULL,
    [debit] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [ADJUSTMENT] (
    [UNIT] INTEGER NOT NULL,
    [ML] INTEGER NOT NULL
);

CREATE TABLE [BackupDrive] (
    [ID] INTEGER NOT NULL,
    [BakDrv] TEXT NOT NULL
);

CREATE TABLE [BILLFINAL] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [TYPE] TEXT NOT NULL,
    [CUST_NAME] TEXT NOT NULL,
    [SERVICE_CHARGE] INTEGER NOT NULL,
    [DISCOUNT] INTEGER NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [BILLDAY] INTEGER NOT NULL,
    [TIME] TIMESTAMP NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [INTIME] TIMESTAMP NOT NULL,
    [CGST] DOUBLE PRECISION NOT NULL,
    [SGST] DOUBLE PRECISION NOT NULL,
    [FOODTOT] INTEGER NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [BILLFINAL_Dayend] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [TYPE] TEXT NOT NULL,
    [CUST_NAME] TEXT NOT NULL,
    [SERVICE_CHARGE] INTEGER NOT NULL,
    [DISCOUNT] INTEGER NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [BILLDAY] INTEGER NOT NULL,
    [TIME] TIMESTAMP NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [INTIME] TIMESTAMP NOT NULL,
    [CGST] DOUBLE PRECISION NOT NULL,
    [SGST] DOUBLE PRECISION NOT NULL,
    [FOODTOT] INTEGER NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [BILLKOT] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [PRINT] INTEGER NOT NULL,
    [UID] INTEGER NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [BILLREF] TEXT NOT NULL,
    [TOpen] INTEGER NOT NULL
);

CREATE TABLE [BILLKOT_TBLSHOW] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [PRINT] INTEGER NOT NULL,
    [UID] INTEGER NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [BILLREF] TEXT NOT NULL,
    [TOpen] INTEGER NOT NULL
);

CREATE TABLE [BILLREPORT] (
    [BILLNO] TEXT NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [AMOUNT] INTEGER NOT NULL,
    [DATE] TEXT NOT NULL,
    [INTIME] TEXT NOT NULL,
    [OUTTIME] TEXT NOT NULL
);

CREATE TABLE [BRANDML] (
    [BRAND] TEXT NOT NULL,
    [ML] INTEGER NOT NULL,
    [TOTALML] INTEGER NOT NULL
);

CREATE TABLE [BtPerCase] (
    [Unit] INTEGER NOT NULL,
    [CaseBott] INTEGER NOT NULL
);

CREATE TABLE [CancelKot] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [Date] TIMESTAMP NOT NULL,
    [waiter] TEXT NOT NULL
);

CREATE TABLE [CashBookOpen] (
    [date] TIMESTAMP NOT NULL,
    [type] TEXT NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [CashTransfer] (
    [code] INTEGER NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [creditTo] TEXT NOT NULL,
    [crname] TEXT NOT NULL,
    [debit] TEXT NOT NULL,
    [dbname] TEXT NOT NULL,
    [narr] TEXT NOT NULL
);

CREATE TABLE [cBilNumber] (
    [ID] INTEGER NOT NULL,
    [ExbilNmbr] INTEGER NOT NULL,
    [ExSrNmbr] INTEGER NOT NULL,
    [RefNo] INTEGER NOT NULL
);

CREATE TABLE [CNTLOOSE] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [TOTALML] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL
);

CREATE TABLE [CNTLOOSE_LIVE] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [TOTALML] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL
);

CREATE TABLE [CNTLOOSE_LIVE_111] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [TOTALML] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL
);

CREATE TABLE [CNTPACK] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL
);

CREATE TABLE [CNTPACK_LIVE] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL,
    [Opnbotlqty] INTEGER NOT NULL,
    [AddAdjml] INTEGER NOT NULL,
    [MinusAdjml] INTEGER NOT NULL,
    [DATE1] TIMESTAMP NOT NULL
);

CREATE TABLE [CNTPACK_LIVE_222] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL,
    [Opnbotlqty] INTEGER NOT NULL,
    [AddAdjml] INTEGER NOT NULL,
    [MinusAdjml] INTEGER NOT NULL,
    [DATE1] TIMESTAMP NOT NULL
);

CREATE TABLE [CNTPACK_LIVE_DAYEND] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL,
    [Opnbotlqty] INTEGER NOT NULL,
    [AddAdjml] INTEGER NOT NULL,
    [MinusAdjml] INTEGER NOT NULL,
    [DATE1] TIMESTAMP NOT NULL
);

CREATE TABLE [CNTPACK1] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL
);

CREATE TABLE [CntRecieved] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [Received] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [CLIENTID] DOUBLE PRECISION NOT NULL,
    [RefNo] INTEGER NOT NULL
);

CREATE TABLE [CntRecieved_N] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [Received] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [CLIENTID] DOUBLE PRECISION NOT NULL,
    [RefNo] INTEGER NOT NULL
);

CREATE TABLE [ContactList] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [phone] TEXT NOT NULL,
    [ListSelsected] INTEGER NOT NULL,
    [RelationType] TEXT NOT NULL,
    [dob] TIMESTAMP NOT NULL,
    [WeadingAni_Date] TIMESTAMP NOT NULL,
    [Occuption] TEXT NOT NULL,
    [debit] INTEGER NOT NULL
);

CREATE TABLE [ContactList_Temp] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [phone] TEXT NOT NULL
);

CREATE TABLE [CounterSockDayend] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OOPEN] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL,
    [Date] TIMESTAMP NOT NULL
);

CREATE TABLE [Customer] (
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [phone] INTEGER NOT NULL,
    [schedule] TEXT NOT NULL,
    [card] INTEGER NOT NULL,
    [discount] INTEGER NOT NULL,
    [code] INTEGER NOT NULL,
    [creditbal] INTEGER NOT NULL,
    [debitbal] INTEGER NOT NULL,
    [customer] TEXT NOT NULL,
    [vendor] TEXT NOT NULL
);

CREATE TABLE [dateLckMaster] (
    [ID] INTEGER,
    [datefrom] TIMESTAMP NOT NULL,
    [dateto] TIMESTAMP NOT NULL,
    [temppassword] TEXT NOT NULL,
    [masterpassword] TEXT NOT NULL
);

CREATE TABLE [datelock] (
    [ID] INTEGER NOT NULL,
    [datefrom] TIMESTAMP NOT NULL,
    [dateto] TIMESTAMP NOT NULL,
    [datefirstlock] TIMESTAMP NOT NULL,
    [datesecondlock] TIMESTAMP NOT NULL,
    [firstlock] INTEGER NOT NULL,
    [secondlock] INTEGER NOT NULL,
    [firstlockpassword] TEXT NOT NULL,
    [secondlockpassword] TEXT NOT NULL
);

CREATE TABLE [DAYEND] (
    [ID] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [Deal_Name] (
    [code] INTEGER,
    [DealNm] TEXT NOT NULL
);

CREATE TABLE [dk] (
    [BILLFINAL_BILLNO] INTEGER NOT NULL,
    [BILLFINAL_TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [BILLFINAL_DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [TYPE] TEXT NOT NULL,
    [CUST_NAME] TEXT NOT NULL,
    [SERVICE_CHARGE] INTEGER NOT NULL,
    [DISCOUNT] INTEGER NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [BILLDAY] INTEGER NOT NULL,
    [finalbill_BILLNO] INTEGER NOT NULL,
    [finalbill_TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [finalbill_DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [DryDates] (
    [code] INTEGER NOT NULL,
    [Dates] TIMESTAMP NOT NULL
);

CREATE TABLE [ExciseBilNumber] (
    [ID] INTEGER NOT NULL,
    [ExbilNmbr] INTEGER NOT NULL,
    [ExSrNmbr] INTEGER NOT NULL
);

CREATE TABLE [ExciseClosingAutoSale] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Receive] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE1] TIMESTAMP NOT NULL,
    [ClosingCurrent] INTEGER NOT NULL
);

CREATE TABLE [ExciseInfo] (
    [PreHldCode] INTEGER NOT NULL,
    [LastExDate] TIMESTAMP NOT NULL,
    [TmlLimit] TEXT NOT NULL,
    [QtyLimit] TEXT NOT NULL
);

CREATE TABLE [ExciseMonthlyStat] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [OPENINGMONTH] INTEGER NOT NULL,
    [RECEIVEDMONTH] INTEGER NOT NULL,
    [RECEIVED1APR] INTEGER NOT NULL,
    [SELLMONTH] INTEGER NOT NULL,
    [SELL1APR] INTEGER NOT NULL,
    [BREAKAGE] INTEGER NOT NULL,
    [CLOSINGMONTH] INTEGER NOT NULL
);

CREATE TABLE [ExciseOpening] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [ExciseOpening_B] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [ExciseOpeningTemp] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [RECIEVED] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [SALELOOSE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [CLOSINGLOOSE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [TOTALLOOSE] INTEGER NOT NULL
);

CREATE TABLE [ExcisePath] (
    [ID] INTEGER NOT NULL,
    [path] TEXT NOT NULL
);

CREATE TABLE [ExFinalBill] (
    [srno] INTEGER NOT NULL,
    [invoice] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [name] TEXT NOT NULL,
    [license] INTEGER NOT NULL,
    [validity] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [ExFinalBillDetails] (
    [srno] INTEGER NOT NULL,
    [invoice] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [item] TEXT NOT NULL,
    [qty] INTEGER NOT NULL,
    [rate] DOUBLE PRECISION NOT NULL,
    [amt] INTEGER NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [brand] TEXT NOT NULL
);

CREATE TABLE [ExFinalBillDetailsTemp] (
    [srno] INTEGER,
    [invoice] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [item] TEXT NOT NULL,
    [qty] INTEGER NOT NULL,
    [rate] DOUBLE PRECISION NOT NULL,
    [amt] INTEGER NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [brand] TEXT NOT NULL
);

CREATE TABLE [ExFinalBillTemp] (
    [srno] INTEGER NOT NULL,
    [invoice] INTEGER,
    [date] TIMESTAMP NOT NULL,
    [name] TEXT NOT NULL,
    [license] INTEGER NOT NULL,
    [validity] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [ExPremiteHolder] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [licence] INTEGER NOT NULL,
    [validity] TEXT NOT NULL,
    [phone] TEXT NOT NULL,
    [Address] TEXT NOT NULL,
    [credit] DOUBLE PRECISION NOT NULL,
    [debit] DOUBLE PRECISION NOT NULL,
    [Issued] TIMESTAMP NOT NULL,
    [Expiry] TIMESTAMP NOT NULL
);

CREATE TABLE [ExStoreInfo] (
    [code] INTEGER NOT NULL,
    [PerHldId] TEXT NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [dateopening] TIMESTAMP NOT NULL,
    [MlLimit] TEXT NOT NULL,
    [QtyLimit] TEXT NOT NULL,
    [exyear] TEXT NOT NULL,
    [SelfDate] TIMESTAMP NOT NULL
);

CREATE TABLE [ExTemp] (
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL
);

CREATE TABLE [ExUnitLimit] (
    [Unit] INTEGER NOT NULL,
    [Limit] TEXT NOT NULL
);

CREATE TABLE [finalbill] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbill_Dayend] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbill_Excise] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbill_Excise1] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbill_LoosAmt] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbillcopy] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [finalbillcopy_Dayend] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [FoodIssue] (
    [code] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [issueto] TEXT NOT NULL,
    [name] TEXT NOT NULL,
    [qty] INTEGER NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [FoodPurchase] (
    [code] INTEGER NOT NULL,
    [tpno] INTEGER NOT NULL,
    [billno] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [packing] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [qty] INTEGER NOT NULL,
    [rate] DOUBLE PRECISION NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [FoodPurchaseFinal] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [tpno] INTEGER NOT NULL,
    [tpdate] TIMESTAMP NOT NULL,
    [billno] INTEGER NOT NULL,
    [billdate] TIMESTAMP NOT NULL,
    [carting] DOUBLE PRECISION NOT NULL,
    [extracharge] DOUBLE PRECISION NOT NULL,
    [discount] DOUBLE PRECISION NOT NULL,
    [total] DOUBLE PRECISION NOT NULL,
    [taxamt] DOUBLE PRECISION NOT NULL,
    [invamt] DOUBLE PRECISION NOT NULL,
    [paytype] TEXT NOT NULL
);

CREATE TABLE [FoodStock] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [Recieved] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [GodownStock] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [Recieved] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [GrandBill] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [TYPE] TEXT NOT NULL,
    [CUST_NAME] TEXT NOT NULL,
    [SERVICE_CHARGE] INTEGER NOT NULL,
    [DISCOUNT] INTEGER NOT NULL,
    [TOTAL] TEXT NOT NULL,
    [BILLDAY] INTEGER NOT NULL,
    [TIME] TIMESTAMP NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [INTIME] TIMESTAMP NOT NULL,
    [CGST] DOUBLE PRECISION NOT NULL,
    [SGST] DOUBLE PRECISION NOT NULL,
    [FOODTOT] INTEGER NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [GrandBillDetails] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [GrandBillDetailscopy] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [GrandBillDetailscopy_Dayend] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [HotelInfo] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [city] TEXT NOT NULL,
    [licno] TEXT NOT NULL,
    [RuleUsed] TEXT NOT NULL,
    [RuleHeading] TEXT NOT NULL,
    [Vattin] TEXT NOT NULL,
    [upi_id] TEXT NOT NULL,
    [BankAcName] TEXT NOT NULL,
    [beer] TEXT NOT NULL,
    [Exciseaddress] TEXT NOT NULL,
    [exname] TEXT NOT NULL,
    [exadd] TEXT NOT NULL,
    [AdminMobile] TEXT NOT NULL,
    [Email] TEXT NOT NULL
);

CREATE TABLE [item] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [exciserate] INTEGER NOT NULL,
    [purchaserate] INTEGER NOT NULL,
    [bottel] INTEGER NOT NULL,
    [openingstock] INTEGER NOT NULL,
    [FAMILYRATE] INTEGER NOT NULL,
    [VIPRATE] INTEGER NOT NULL,
    [ACRATE] INTEGER NOT NULL,
    [WHOLESALE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [Marathi] TEXT NOT NULL,
    [IT_CODE] TEXT NOT NULL
);

CREATE TABLE [ItemDept] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [child] INTEGER NOT NULL,
    [setup] INTEGER NOT NULL,
    [id] INTEGER NOT NULL,
    [printer] TEXT NOT NULL
);

CREATE TABLE [k] (
    [ID] INTEGER NOT NULL,
    [PATH] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL
);

CREATE TABLE [KOT] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DEPT] TEXT NOT NULL
);

CREATE TABLE [KOTDETAIL] (
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [KOTNO] TEXT NOT NULL
);

CREATE TABLE [KOTDETAIL_DAYEND] (
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [KOTNO] TEXT NOT NULL
);

CREATE TABLE [KOTFINAL] (
    [KOTNO] TEXT NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DAYKOT] TEXT NOT NULL
);

CREATE TABLE [KOTFINAL_DAYEND] (
    [KOTNO] TEXT NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DAYKOT] TEXT NOT NULL
);

CREATE TABLE [KOTTEMP] (
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL
);

CREATE TABLE [KOTTOTAL] (
    [ID] INTEGER NOT NULL,
    [TOTAL] INTEGER NOT NULL
);

CREATE TABLE [LiqPurchase] (
    [code] INTEGER NOT NULL,
    [tpno] INTEGER NOT NULL,
    [billno] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [packing] TEXT NOT NULL,
    [unit] TEXT NOT NULL,
    [batchno] INTEGER NOT NULL,
    [qty] INTEGER NOT NULL,
    [bottle] INTEGER NOT NULL,
    [rate] INTEGER NOT NULL,
    [amt] TEXT NOT NULL,
    [brand] TEXT NOT NULL,
    [Billdate] TIMESTAMP NOT NULL,
    [type] TEXT NOT NULL,
    [tpdate2] TIMESTAMP NOT NULL,
    [vndnm] TEXT NOT NULL
);

CREATE TABLE [LiqPurchaseFinal] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [tpno] INTEGER NOT NULL,
    [tpdate] TIMESTAMP NOT NULL,
    [billno] INTEGER NOT NULL,
    [billdate] TIMESTAMP NOT NULL,
    [stampduty] DOUBLE PRECISION NOT NULL,
    [cd] DOUBLE PRECISION NOT NULL,
    [scheme] DOUBLE PRECISION NOT NULL,
    [stocktran] DOUBLE PRECISION NOT NULL,
    [carting] DOUBLE PRECISION NOT NULL,
    [saleta] DOUBLE PRECISION NOT NULL,
    [cs] DOUBLE PRECISION NOT NULL,
    [sc] DOUBLE PRECISION NOT NULL,
    [edu] DOUBLE PRECISION NOT NULL,
    [total] DOUBLE PRECISION NOT NULL,
    [taxamt] DOUBLE PRECISION NOT NULL,
    [invamt] DOUBLE PRECISION NOT NULL,
    [tpDate2] TIMESTAMP NOT NULL
);

CREATE TABLE [Login] (
    [code] INTEGER NOT NULL,
    [Uname] TEXT NOT NULL,
    [passward] TEXT NOT NULL,
    [clientid] TEXT NOT NULL
);

CREATE TABLE [Message] (
    [ID] INTEGER NOT NULL,
    [messageText] TEXT NOT NULL
);

CREATE TABLE [NewBank] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [acno] TEXT NOT NULL,
    [shortname] TEXT NOT NULL,
    [place] TEXT NOT NULL,
    [cclimit] INTEGER NOT NULL,
    [phone] TEXT NOT NULL,
    [credit] DOUBLE PRECISION NOT NULL,
    [debit] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [NewCustomer] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [phone] TEXT NOT NULL,
    [schedule] TEXT NOT NULL,
    [card] INTEGER NOT NULL,
    [discount] INTEGER NOT NULL,
    [codeno] INTEGER NOT NULL,
    [credit] INTEGER NOT NULL,
    [debit] INTEGER NOT NULL
);

CREATE TABLE [NewFood] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [packing] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [rate] INTEGER NOT NULL
);

CREATE TABLE [NewVendor] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [phone] TEXT NOT NULL,
    [credit] INTEGER NOT NULL,
    [debit] INTEGER NOT NULL,
    [type] TEXT NOT NULL
);

CREATE TABLE [OtherPurchase] (
    [code] INTEGER NOT NULL,
    [tpno] INTEGER NOT NULL,
    [billno] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [packing] TEXT NOT NULL,
    [unit] TEXT NOT NULL,
    [batchno] INTEGER NOT NULL,
    [qty] INTEGER NOT NULL,
    [bottle] INTEGER NOT NULL,
    [rate] INTEGER NOT NULL,
    [amt] TEXT NOT NULL,
    [brand] TEXT NOT NULL,
    [Billdate] TIMESTAMP NOT NULL,
    [type] TEXT NOT NULL
);

CREATE TABLE [OtherPurchaseFinal] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [tpno] INTEGER NOT NULL,
    [tpdate] TIMESTAMP NOT NULL,
    [billno] INTEGER NOT NULL,
    [billdate] TIMESTAMP NOT NULL,
    [stampduty] DOUBLE PRECISION NOT NULL,
    [cd] DOUBLE PRECISION NOT NULL,
    [scheme] DOUBLE PRECISION NOT NULL,
    [stocktran] DOUBLE PRECISION NOT NULL,
    [carting] DOUBLE PRECISION NOT NULL,
    [saleta] DOUBLE PRECISION NOT NULL,
    [cs] DOUBLE PRECISION NOT NULL,
    [sc] DOUBLE PRECISION NOT NULL,
    [edu] DOUBLE PRECISION NOT NULL,
    [total] DOUBLE PRECISION NOT NULL,
    [taxamt] DOUBLE PRECISION NOT NULL,
    [invamt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [Paste Errors] (
    [code] TEXT NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [exciserate] INTEGER NOT NULL,
    [purchaserate] INTEGER NOT NULL,
    [bottel] INTEGER NOT NULL,
    [openingstock] INTEGER NOT NULL,
    [FAMILYRATE] INTEGER NOT NULL,
    [VIPRATE] INTEGER NOT NULL,
    [ACRATE] INTEGER NOT NULL,
    [WHOLESALE] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [Marathi] TEXT NOT NULL,
    [VENDOR] TEXT NOT NULL,
    [ExcBrandName] TEXT NOT NULL,
    [ExcCode] TEXT NOT NULL
);

CREATE TABLE [Payment] (
    [code] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [name] TEXT NOT NULL,
    [narr] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [cq_dd_no] TEXT NOT NULL,
    [commision] DOUBLE PRECISION NOT NULL,
    [vendor] TEXT NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [PrintBillCount] (
    [id] INTEGER NOT NULL,
    [billno] INTEGER NOT NULL
);

CREATE TABLE [PRINTERSETUP] (
    [ID] INTEGER NOT NULL,
    [PATH] TEXT NOT NULL
);

CREATE TABLE [product_key] (
    [ID] INTEGER NOT NULL,
    [serialkey] TEXT NOT NULL,
    [pass] TEXT NOT NULL,
    [Field1] TEXT NOT NULL
);

CREATE TABLE [Receipt] (
    [code] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [name] TEXT NOT NULL,
    [narr] TEXT NOT NULL,
    [pay_type] TEXT NOT NULL,
    [cq_dd_no] TEXT NOT NULL,
    [commision] INTEGER NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [rptdept_type] (
    [ITEM] TEXT NOT NULL,
    [QTY] DOUBLE PRECISION NOT NULL,
    [AMOUNT] DOUBLE PRECISION NOT NULL,
    [TYPE] TEXT NOT NULL,
    [DATETO] TIMESTAMP NOT NULL,
    [DATEFROM] TIMESTAMP NOT NULL
);

CREATE TABLE [sectionwise_temp] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [SRNO] INTEGER NOT NULL,
    [ITEM] TEXT NOT NULL,
    [QTY] INTEGER NOT NULL,
    [RATE] INTEGER NOT NULL,
    [AMT] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [DEPT] TEXT NOT NULL,
    [TYPE] TEXT NOT NULL,
    [UNIT] INTEGER NOT NULL,
    [PACKING] TEXT NOT NULL,
    [BRAND] TEXT NOT NULL,
    [BILLTYPE] TEXT NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [sectionwiseBillfinal_Temp] (
    [BILLNO] INTEGER NOT NULL,
    [TABLE_NO] TEXT NOT NULL,
    [WAITER] TEXT NOT NULL,
    [DATE] TIMESTAMP NOT NULL,
    [PAID] INTEGER NOT NULL,
    [TYPE] TEXT NOT NULL,
    [CUST_NAME] TEXT NOT NULL,
    [SERVICE_CHARGE] INTEGER NOT NULL,
    [DISCOUNT] INTEGER NOT NULL,
    [TOTAL] INTEGER NOT NULL,
    [BILLDAY] INTEGER NOT NULL,
    [TIME] TIMESTAMP NOT NULL,
    [CLIENTID] INTEGER NOT NULL,
    [OPERATOR] TEXT NOT NULL,
    [INTIME] TIMESTAMP NOT NULL,
    [CGST] INTEGER NOT NULL,
    [SGST] INTEGER NOT NULL,
    [FOODTOT] INTEGER NOT NULL,
    [SECTIONS] TEXT NOT NULL
);

CREATE TABLE [Setup] (
    [code] INTEGER NOT NULL,
    [kotsetup] INTEGER NOT NULL,
    [codeonoff] INTEGER NOT NULL,
    [CounterCashDisplay] INTEGER NOT NULL,
    [Waiteronoff] INTEGER NOT NULL,
    [ServiceChargeOnOff] INTEGER NOT NULL,
    [DIscountOnOff] INTEGER NOT NULL,
    [Dateshow] INTEGER NOT NULL,
    [DeptKot] INTEGER NOT NULL,
    [ThermalPrint] INTEGER NOT NULL,
    [WineShop] INTEGER NOT NULL,
    [counterStock] INTEGER NOT NULL,
    [LptPrinter] INTEGER NOT NULL,
    [ExciseAddress] SMALLINT NOT NULL,
    [PaidOnOff] INTEGER NOT NULL,
    [Email] INTEGER NOT NULL,
    [MarathiBill] INTEGER NOT NULL,
    [DeptMultiPrinter] INTEGER NOT NULL,
    [BillCorrLock] INTEGER NOT NULL,
    [LiveCntStk] INTEGER NOT NULL,
    [ResturantOnly] INTEGER NOT NULL,
    [Gst] INTEGER NOT NULL,
    [NewVersion] INTEGER NOT NULL,
    [CounterCashAdmin] INTEGER NOT NULL,
    [Sms] INTEGER NOT NULL,
    [Barcode] INTEGER NOT NULL,
    [PrintAllColumn] INTEGER NOT NULL,
    [BillCorrLockBillPaid] INTEGER NOT NULL,
    [BillDeptShow] INTEGER NOT NULL,
    [AutoOpen] INTEGER NOT NULL,
    [MINUSSTOCK] INTEGER NOT NULL,
    [QRCodePrint] INTEGER NOT NULL,
    [SelfDate] INTEGER NOT NULL
);

CREATE TABLE [softkey] (
    [ID] INTEGER NOT NULL,
    [serialkey] TEXT NOT NULL,
    [pass] TEXT NOT NULL,
    [Field1] TEXT NOT NULL
);

CREATE TABLE [SoftwareName] (
    [name] TEXT NOT NULL,
    [vision] TEXT NOT NULL,
    [rss] TEXT NOT NULL
);

CREATE TABLE [STK_CNTR_KEYPRESS] (
    [DATE_TIME_NOW] TEXT NOT NULL,
    [DATE_TIME_ENTER] TEXT NOT NULL
);

CREATE TABLE [stockcheck] (
    [code] INTEGER NOT NULL,
    [item] TEXT NOT NULL,
    [stock] TEXT NOT NULL,
    [dept] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [unit] INTEGER NOT NULL,
    [packing] TEXT NOT NULL,
    [salerate] INTEGER NOT NULL,
    [OPENING] INTEGER NOT NULL,
    [OpenTemp] INTEGER NOT NULL,
    [Purchase] INTEGER NOT NULL,
    [SALE] INTEGER NOT NULL,
    [CLOSING] INTEGER NOT NULL,
    [BRAND] TEXT NOT NULL,
    [TOTALPACK] INTEGER NOT NULL,
    [DATE] TIMESTAMP NOT NULL
);

CREATE TABLE [TABLE_NO_GROP] (
    [ID] INTEGER NOT NULL,
    [GROP] TEXT NOT NULL
);

CREATE TABLE [temp] (
    [code] INTEGER NOT NULL,
    [amtrecipt] INTEGER NOT NULL,
    [amtvoucher] INTEGER NOT NULL
);

CREATE TABLE [Voucher] (
    [code] INTEGER NOT NULL,
    [date] TIMESTAMP NOT NULL,
    [name] TEXT NOT NULL,
    [narr] TEXT NOT NULL,
    [amt] DOUBLE PRECISION NOT NULL
);

CREATE TABLE [Waiter] (
    [code] INTEGER NOT NULL,
    [name] TEXT NOT NULL,
    [address] TEXT NOT NULL,
    [mobile] TEXT NOT NULL,
    [credit] DOUBLE PRECISION NOT NULL,
    [debit] DOUBLE PRECISION NOT NULL
);

